# 全局日志级别
LOG_LEVEL = "debug"

RPC_PREFIX="/api"

OUTER_API_TIMEOUT = 600
INTERNAL_API_TIMEOUT = 600

# opentracing jaeger
JAEGER_AGENT_HOST = "127.0.0.1"
JAEGER_AGENT_PORT = "6831"

# jwt
JWT_SIGNING_METHOD = "HS512"
JWT_SIGNING_KEY = "签名秘钥"
JWT_EFFECTIVE_DURATION = 259200 # 秒为单位默认3天
