# 全局日志级别
LOG_LEVEL = "debug"

RPC_PREFIX="/api"

# DB 配置，格式为 DB_${NAME}_DSN，内容参考
# https://github.com/go-sql-driver/mysql#dsn-data-source-name
# 必须设置 parseTime 选项
# 通过 ${NAME} 可以获取 DB 连接池
# 时区问题参考 https://www.jianshu.com/p/3f7fc9093db4
DB_DEFAULT_DSN = "foo:bar@tcp(127.0.0.1:3306)/baz?parseTime=true&loc=Local"

# Redis 配置
REDIS_DEFAULT_HOST = "127.0.0.1:6379"
# 初始连接数
REDIS_DEFAULT_INIT_CONNS = 1
# 最大连接数
REDIS_DEFAULT_MAX_CONNS = 2

OUTER_API_TIMEOUT = 600
INTERNAL_API_TIMEOUT = 600

# opentracing jaeger
JAEGER_AGENT_HOST = "127.0.0.1"
JAEGER_AGENT_PORT = "6831"

# jwt
JWT_SIGNING_METHOD = "HS512"
JWT_SIGNING_KEY = "签名秘钥"
JWT_EFFECTIVE_DURATION = 259200 # 秒为单位默认3天
